name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: learning
  CONTAINER_NAME: learning-devops
  IMAGE_NAME: learning-devops
  IMAGE_TAG: ${GITHUB_SHA::7}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
