name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -f Dockerfile.dev -t pshrestha/react_app .

      - name: Save Docker Image as Artifact
        run: docker save pshrestha/react_app:latest > react_app.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pshrestha
          path: react_app.tar

  test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: pshrestha

      - name: Load Docker Image from Artifact
        run: docker load < react_app.tar

      - name: Run Tests in Docker Container
        run: docker run -e CI=true pshrestha/react_app npm test
